# These are the default code conventions for Panorama Ruby projects.
#
# You can use this in your project's .rubocop.yml with the following at the top:
#
#     inherit_gem:
#       panolint: .rubocop.yml
#
# This allows you to selectively override settings in projects, for example, if
# you're working on a Sinatra project, disabling the Rails cops is probably
# something that you would want to do.
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - !ruby/regexp /vendor\/(?!panoramaed).*$/
    - "db/schema.rb"
    - "db/migrate/**/*"

Layout/DotPosition:
  EnforcedStyle: trailing

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/Debugger:
  Severity: error

Lint/SuppressedException:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - bin/exports/spec/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 80
  IgnoreCopDirectives: true

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 10

Naming/BinaryOperatorParameterName:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/**/*

Style/MultilineBlockChain:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NotToNot:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
